# using try and except block for exception handling 

name = "Krishna "
try:
    print(name)
except:
    print("Error Ocurred")